version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
#   Command to run our application
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${NAME}
      - DB_USER=${USER}
      - DB_PASS=${PASSCODE}
      - SECRET_KEY=${SECRET_KEY}
      - USER_EMAIL=${EMAIL}
      - USER_NAME=${USERNAME}
      - USER_FNAME=${F_NAME}
      - USER_LNAME=${L_NAME}
      - USER_PASS=${PASSWORD}
      - NEW_USER_NAME=${UPDATED_NAME}
      - NEW_USER_PASS=${UPDATED_PASS}
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${NAME}
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${PASSCODE}
