# Generated by Django 3.2.4 on 2021-06-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='username',
            new_name='tag_name',
        ),
    ]
