# Generated by Django 3.2.4 on 2021-06-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_username_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='username',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ing_name',
            field=models.CharField(max_length=255, verbose_name='ing_name'),
        ),
    ]
