# Generated by Django 3.2.4 on 2021-06-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210626_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='ingredient_fk',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tags',
            new_name='tag_fk',
        ),
    ]
